### ISSUE TITLE
Bus Tickets - City Input Quantity 

### ISSUE THREAD

**Issue by chanashear95** [kob-e/exercises#1]
How many cities should the user have to choose from?

**Comment by boruxk** [comment]
maybe this?
https://gist.github.com/Miserlou/c5cd8364bf9b2420bb29
Yakov wanted to give us a db, maybe there are all the cities

**Comment by YaakovHatam** [comment]
From all the cities available from and all the cities available to.
for example:
consider the data

``` json
[
{
     "from": "new york",
     "to": "new jersey"
},
{
     "from": "new york",
     "to": "washington"
}
]
```

So in **from** dropdown you should give the options for **new york**

and **to** dropdown should have **new jersey** and **washington**
